# Generated by Django 4.1.7 on 2023-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
    ]
